### ISSUE TITLE
Errors loading OML file

### ISSUE THREAD

**Issue by whicken** [teverett/OLMReader#2]
I'm hitting several issues loading an .oml file, it looks as if the schema might have been extended.

First, for some of the boolean elements, my exported document (from Outlook for Mac) has the value "0E0". This fails validation, as the parser doesn't recognize it. (From googling, it appears to be a way to represent a value with is both 0 and true). As a quick hack, I changed all the boolean elements to strings to continue testing.

Second, I hit a number of new elements:
OPFMessageGetInferenceClassification
OPFMessageGetMentionedMe
OPFMessageGetSendReadReceipt
OPFMessageCopyThreadIndex

When I made both these changes to the schema, it can now process my file. Let me know if you'd like additional information.

Thanks for providing the library!!!

**Comment by teverett** [comment]
@whicken thanks for the changes.  Are you planning to submit a pull request?

**Comment by whicken** [comment]
I'll submit that once I have my project working, in case I come across any other changes.

I did also disable a println inside the library, that's just a nuisance. It might be better placed into the OLMReader example.

**Comment by teverett** [comment]
All good.  I'll wait on the pull request.

**Comment by teverett** [comment]
@whicken any progress on the potential pull request?
