### ISSUE TITLE
Issue building on Amazon Machine Image (AMI) 

### ISSUE THREAD

**Issue by paulfryer** [teverett/OLMReader#4]
I'm using cloud9 trying to build this project, getting this error. Hoping you can help here?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.654 s
[INFO] Finished at: 2018-03-14T16:30:16Z
[INFO] Final Memory: 36M/418M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project olmreader: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.151.x86_64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/ec2-user/environment/OLMReader/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project olmreader: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none

Command line was: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.151.x86_64/jre/../bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/ec2-user/environment/OLMReader/target/apidocs' dir.

**Comment by teverett** [comment]
looks like it's having an issue with `Xdoclint:none`.

Comment this out in pom.xml and see what happens

```
<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>2.10.3</version>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<additionalparam>-Xdoclint:none</additionalparam>
						</configuration>
					</plugin>
```
