### ISSUE TITLE
Found some new elements for emails.xsd

### ISSUE THREAD

**Issue by culyzhao** [teverett/OLMReader#6]
ExchangeServerLastModifiedTime
OPFMessageCopyDisplayTo
OPFMessageCopyExchangeConversationId
OPFMessageCopyLocalThreadGUID
OPFMessageCopyPreview

**Comment by teverett** [comment]
Thanks for this.  Do you have an example OLM for these, or can you send an
updated xsd?  From the info you provided I'm not sure where to add these in
the xsd or how to validate that the changes are correct.

**Comment by culyzhao** [comment]
my olm file size is very big, attached the updated emails.xsd, these elements have no special attributions
[emails.zip](https://github.com/teverett/OLMReader/files/2735012/emails.zip)

**Comment by teverett** [comment]
Thanks, the new xsd is added.
