### ISSUE TITLE
Error with OPFContactAddPicture

### ISSUE THREAD

**Issue by R-K-H** [teverett/OLMReader#7]
`Invalid content was found starting with element 'OPFContactAddPicture'`

As well `Invalid content was found starting with element 'OPFContactAddPictureType'`

I'm trying to open an OLM with contacts. It looks like Outlook may have updated the schema.

**Comment by teverett** [comment]
What version of outlook is it?  Can you share a snippet of the OLM with those tags?

**Comment by R-K-H** [comment]
I can give you something truncated. I'm not sure it may be older or something odd... I was handed a file and asked if I can extract the contacts, I'll see if I can find out tomorrow.

```<OPFContactAddPicture xml:space="preserve">/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMA8A [.. much longer..] Z9Wr2Fl+aRxNDmP//R+m9E1zTYLSKx87yru1nT93/eSVdvyf3vlOfXg+lc78ZfhJF4404/Z+buL7kn/sn96uV+JC6+KLb/StK+3SwWUif8ALWDT18qNk9pGBK9fvV9J+Arq5ukMHySi2jSCaR/uN/tJ/D3/ALo6DrXyGfc05+0PtMjjGFL2Z//Z</OPFContactAddPicture><OPFContactAddPictureType xml:space="preserve">1246774599</OPFContactAddPictureType>```

**Comment by R-K-H** [comment]
The export was also weird as there was listed only one contacts, but with the rawoutput I was able to find 51 more. So I'm not sure this export wasn't just weird.

**Comment by teverett** [comment]
If you could tell *where* to add that snippit it would be great, or PR would be even better.

**Comment by R-K-H** [comment]
Sure thing. It will take me a few days I'll submit a PR.
