### ISSUE TITLE
Update Readme with install and operating instructions

### ISSUE THREAD

**Issue by R-K-H** [teverett/OLMReader#8]
Coming from little to no experience with Java, it was a bit of a roundabout to get this up and running. I'd like to update the readme to run through some install instructions. I can do the Mac side of things, like installing the SDK and Maven took a bit to sort out as well some build errors with the `release.sh` and `run_example.sh` which I was able to sort out by running `mvn clean install` and updating the `run_example.sh` to `java -jar target/olmreader-1.6.0-SNAPSHOT.jar` not `1.3`.

I'll fork then put in a PR if it's something you think would be worth while.

**Comment by teverett** [comment]
That would be great!
